function [fitresult, gof] = createFit(a, Pcons_agg)
%CREATEFIT(A,PCONS_AGG)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input: a
%      Y Output: Pcons_agg
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 29-Jul-2024 16:01:19


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( a, Pcons_agg );

% Set up fittype and options.
ft = 'linearinterp';
opts = fitoptions( 'Method', 'LinearInterpolant' );
opts.ExtrapolationMethod = 'linear';
opts.Normalize = 'on';

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, xData, yData );
legend( h, 'Pcons_agg vs. a', 'untitled fit 1', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'a', 'Interpreter', 'none' );
ylabel( 'Pcons_agg', 'Interpreter', 'none' );
grid on


